CREATE TABLE PERIODO (
  idPERIODO INTEGER NOT NULL,
  horaIni TIME NULL,
  horaFin TIME NULL,
  dia DATE NULL,
  PRIMARY KEY(idPERIODO)
);

CREATE TABLE ESPECIALIDAD (
  idESPECIALIDAD INTEGER NOT NULL,
  nombreEspecialidad VARCHAR(20) NULL,
  PRIMARY KEY(idESPECIALIDAD)
);

CREATE TABLE TIPO_PARTICIPANTE (
  idTIPO_PARTICIPANTE INTEGER NOT NULL,
  nobreTipoParticipante VARCHAR(20) NULL,
  PRIMARY KEY(idTIPO_PARTICIPANTE)
);

CREATE TABLE PATROCINADOR (
  idPATROCINADOR INTEGER NOT NULL,
  nobrePatrocinador VARCHAR(20) NULL,
  PRIMARY KEY(idPATROCINADOR)
);

CREATE TABLE OFERTA (
  idOFERTA INTEGER NOT NULL,
  precio INTEGER NULL,
  fechaIni DATE NULL,
  fechaFin DATE NULL,
  numeroMinimo INTEGER NULL,
  PRIMARY KEY(idOFERTA)
);

CREATE TABLE TIPO_AMBIENTE (
  idTIPO_AMBIENTE INTEGER NOT NULL,
  NombreTipoAmbiente VARCHAR(20) NULL,
  PRIMARY KEY(idTIPO_AMBIENTE)
);

CREATE TABLE TIPO_PATROCINIO (
  idTIPO_PATROCINIO VARCHAR(20) NOT NULL,
  PRIMARY KEY(idTIPO_PATROCINIO)
);

CREATE TABLE CURSO (
  idCURSO INTEGER NOT NULL,
  tema VARCHAR(20) NULL,
  descripcion VARCHAR(20) NULL,
  valorCurricular BOOL NULL,
  duracion REAL NULL,
  cupo INTEGER NULL,
  PRIMARY KEY(idCURSO)
);

CREATE TABLE ANUNCIO (
  idANUNCIO INTEGER NOT NULL,
  contenido VARCHAR(255) NULL,
  fechaAnuncio DATE NULL,
  PRIMARY KEY(idANUNCIO)
);

CREATE TABLE DISERTANTE (
  idDISERTANTE INTEGER NOT NULL,
  nombreDisertante VARCHAR(20) NULL,
  PRIMARY KEY(idDISERTANTE)
);

CREATE TABLE AMBIENTE (
  idAMBIENTE INTEGER NOT NULL,
  TIPO_AMBIENTE_idTIPO_AMBIENTE INTEGER NOT NULL,
  lugar VARCHAR(20) NULL,
  PRIMARY KEY(idAMBIENTE),
  FOREIGN KEY(TIPO_AMBIENTE_idTIPO_AMBIENTE)
    REFERENCES TIPO_AMBIENTE(idTIPO_AMBIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PARTICIPANTE (
  idPARTICIPANTE INTEGER NOT NULL,
  TIPO_PARTICIPANTE_idTIPO_PARTICIPANTE INTEGER NOT NULL,
  PRIMARY KEY(idPARTICIPANTE),
  FOREIGN KEY(TIPO_PARTICIPANTE_idTIPO_PARTICIPANTE)
    REFERENCES TIPO_PARTICIPANTE(idTIPO_PARTICIPANTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PATROCINIO (
  CURSO_idCURSO INTEGER NOT NULL,
  PATROCINADOR_idPATROCINADOR INTEGER NOT NULL,
  PRIMARY KEY(CURSO_idCURSO, PATROCINADOR_idPATROCINADOR),
  FOREIGN KEY(CURSO_idCURSO)
    REFERENCES CURSO(idCURSO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PATROCINADOR_idPATROCINADOR)
    REFERENCES PATROCINADOR(idPATROCINADOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ESPECIALIZACION (
  DISERTANTE_idDISERTANTE INTEGER NOT NULL,
  ESPECIALIDAD_idESPECIALIDAD INTEGER NOT NULL,
  PRIMARY KEY(DISERTANTE_idDISERTANTE, ESPECIALIDAD_idESPECIALIDAD),
  FOREIGN KEY(DISERTANTE_idDISERTANTE)
    REFERENCES DISERTANTE(idDISERTANTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ESPECIALIDAD_idESPECIALIDAD)
    REFERENCES ESPECIALIDAD(idESPECIALIDAD)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE INSCRIPCION (
  fechaInscripcion DATE NOT NULL,
  OFERTA_idOFERTA INTEGER NOT NULL,
  CURSO_idCURSO INTEGER NOT NULL,
  PARTICIPANTE_idPARTICIPANTE INTEGER NOT NULL,
  PRIMARY KEY(fechainscripcion, OFERTA_idOFERTA, CURSO_idCURSO, PARTICIPANTE_idPARTICIPANTE),
  FOREIGN KEY(PARTICIPANTE_idPARTICIPANTE)
    REFERENCES PARTICIPANTE(idPARTICIPANTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(OFERTA_idOFERTA)
    REFERENCES OFERTA(idOFERTA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CURSO_idCURSO)
    REFERENCES CURSO(idCURSO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE CLASE (
  idCLASE DATE NOT NULL,
  DISERTANTE_idDISERTANTE INTEGER NOT NULL,
  AMBIENTE_idAMBIENTE INTEGER NOT NULL,
  CURSO_idCURSO INTEGER NOT NULL,
  PRIMARY KEY(idCLASE, DISERTANTE_idDISERTANTE, AMBIENTE_idAMBIENTE, CURSO_idCURSO),
  FOREIGN KEY(DISERTANTE_idDISERTANTE)
    REFERENCES DISERTANTE(idDISERTANTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(AMBIENTE_idAMBIENTE)
    REFERENCES AMBIENTE(idAMBIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CURSO_idCURSO)
    REFERENCES CURSO(idCURSO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DETALLE_PATROCINIO (
  PATROCINIO_PATROCINADOR_idPATROCINADOR INTEGER NOT NULL,
  PATROCINIO_CURSO_idCURSO INTEGER NOT NULL,
  TIPO_PATROCINIO_idTIPO_PATROCINIO VARCHAR(20) NOT NULL,
  cantidad INTEGER NULL,
  PRIMARY KEY(PATROCINIO_PATROCINADOR_idPATROCINADOR, PATROCINIO_CURSO_idCURSO),
  FOREIGN KEY(PATROCINIO_CURSO_idCURSO, PATROCINIO_PATROCINADOR_idPATROCINADOR)
    REFERENCES PATROCINIO(CURSO_idCURSO, PATROCINADOR_idPATROCINADOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TIPO_PATROCINIO_idTIPO_PATROCINIO)
    REFERENCES TIPO_PATROCINIO(idTIPO_PATROCINIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION

);

CREATE TABLE DURACION (
  idDURACION INTEGER NOT NULL,
  CLASE_idCLASE DATE NOT NULL,
  CLASE_CURSO_idCURSO INTEGER NOT NULL,
  CLASE_AMBIENTE_idAMBIENTE INTEGER NOT NULL,
  CLASE_DISERTANTE_idDISERTANTE INTEGER NOT NULL,
  PERIODO_idPERIODO INTEGER NOT NULL,
  PRIMARY KEY(idDURACION, CLASE_idCLASE, CLASE_CURSO_idCURSO, CLASE_AMBIENTE_idAMBIENTE, CLASE_DISERTANTE_idDISERTANTE, PERIODO_idPERIODO),
  FOREIGN KEY(CLASE_idCLASE, CLASE_DISERTANTE_idDISERTANTE, CLASE_AMBIENTE_idAMBIENTE, CLASE_CURSO_idCURSO)
    REFERENCES CLASE(idCLASE, DISERTANTE_idDISERTANTE, AMBIENTE_idAMBIENTE, CURSO_idCURSO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PERIODO_idPERIODO)
    REFERENCES PERIODO(idPERIODO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);
