CREATE TABLE PERIODO (
  idPERIODO SERIAL,
  horaIni TIME,
  horaFin TIME,
  PRIMARY KEY(idPERIODO)
);

CREATE TABLE ESPECIALIDAD (
  idESPECIALIDAD SERIAL,
  nombreEspecialidad VARCHAR(20),
  PRIMARY KEY(idESPECIALIDAD)
);

CREATE TABLE TIPO_PARTICIPANTE (
  idTIPO_PARTICIPANTE SERIAL,
  nobreTipoParticipante VARCHAR(20),
  PRIMARY KEY(idTIPO_PARTICIPANTE)
);

CREATE TABLE PATROCINADOR (
  idPATROCINADOR SERIAL,
  nobrePatrocinador VARCHAR(20),
  PRIMARY KEY(idPATROCINADOR)
);

CREATE TABLE OFERTA (
  idOFERTA SERIAL,
  precio INTEGER,
  fechaIni DATE,
  fechaFin DATE,
  numeroMinimo INTEGER,
  PRIMARY KEY(idOFERTA)
);

CREATE TABLE TIPO_AMBIENTE (
  idTIPO_AMBIENTE SERIAL,
  NombreTipoAmbiente VARCHAR(20),
  PRIMARY KEY(idTIPO_AMBIENTE)
);

CREATE TABLE TIPO_PATROCINIO (
  idTIPO_PATROCINIO VARCHAR(20),
  PRIMARY KEY(idTIPO_PATROCINIO)
);

CREATE TABLE CURSO (
  idCURSO SERIAL,
  tema VARCHAR(20),
  descripcion VARCHAR(20),
  valorCurricular BOOL,
  duracion REAL,
  cupo INTEGER,
  PRIMARY KEY(idCURSO)
);

CREATE TABLE ANUNCIO (
  idANUNCIO SERIAL,
  contenido VARCHAR(255),
  fechaAnuncio DATE,
  PRIMARY KEY(idANUNCIO)
);

CREATE TABLE DISERTANTE (
  idDISERTANTE SERIAL,
  nombreDisertante VARCHAR(20),
  apellidosDisertante VARCHAR(20),
  PRIMARY KEY(idDISERTANTE)
);

CREATE TABLE AMBIENTE (
  idAMBIENTE SERIAL,
  TIPO_AMBIENTE_idTIPO_AMBIENTE INTEGER,
  lugar VARCHAR(20),
  nombreAmbiente VARCHAR(20),
  PRIMARY KEY(idAMBIENTE),
  FOREIGN KEY(TIPO_AMBIENTE_idTIPO_AMBIENTE)
    REFERENCES TIPO_AMBIENTE(idTIPO_AMBIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PARTICIPANTE (
  ciPARTICIPANTE INTEGER,
  TIPO_PARTICIPANTE_idTIPO_PARTICIPANTE INTEGER,
  nombreParticipante VARCHAR(20),
  apellidosParticipante VARCHAR(20),
  PRIMARY KEY(idPARTICIPANTE),
  FOREIGN KEY(TIPO_PARTICIPANTE_idTIPO_PARTICIPANTE)
    REFERENCES TIPO_PARTICIPANTE(idTIPO_PARTICIPANTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PATROCINIO (
  CURSO_idCURSO INTEGER,
  PATROCINADOR_idPATROCINADOR INTEGER,
  PRIMARY KEY(CURSO_idCURSO, PATROCINADOR_idPATROCINADOR),
  FOREIGN KEY(CURSO_idCURSO)
    REFERENCES CURSO(idCURSO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PATROCINADOR_idPATROCINADOR)
    REFERENCES PATROCINADOR(idPATROCINADOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ESPECIALIZACION (
  DISERTANTE_idDISERTANTE INTEGER,
  ESPECIALIDAD_idESPECIALIDAD INTEGER,
  PRIMARY KEY(DISERTANTE_idDISERTANTE, ESPECIALIDAD_idESPECIALIDAD),
  FOREIGN KEY(DISERTANTE_idDISERTANTE)
    REFERENCES DISERTANTE(idDISERTANTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ESPECIALIDAD_idESPECIALIDAD)
    REFERENCES ESPECIALIDAD(idESPECIALIDAD)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE INSCRIPCION (
  OFERTA_idOFERTA INTEGER,
  CURSO_idCURSO INTEGER,
  PARTICIPANTE_idPARTICIPANTE INTEGER,
  fechaInscripcion DATE,
  PRIMARY KEY(OFERTA_idOFERTA, CURSO_idCURSO, PARTICIPANTE_idPARTICIPANTE),
  FOREIGN KEY(PARTICIPANTE_idPARTICIPANTE)
    REFERENCES PARTICIPANTE(idPARTICIPANTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(OFERTA_idOFERTA)
    REFERENCES OFERTA(idOFERTA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CURSO_idCURSO)
    REFERENCES CURSO(idCURSO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE CLASE (
  idCLASE INTEGER,
  DISERTANTE_idDISERTANTE INTEGER,
  AMBIENTE_idAMBIENTE INTEGER,
  CURSO_idCURSO INTEGER,
  PERIODO_idPERIODO INTEGER,
  dia DATE,
  PRIMARY KEY(idCLASE, DISERTANTE_idDISERTANTE, AMBIENTE_idAMBIENTE, CURSO_idCURSO, PERIODO_idPERIODO),
  FOREIGN KEY(DISERTANTE_idDISERTANTE)
    REFERENCES DISERTANTE(idDISERTANTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(AMBIENTE_idAMBIENTE)
    REFERENCES AMBIENTE(idAMBIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CURSO_idCURSO)
    REFERENCES CURSO(idCURSO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PERIODO_idPERIODO)
    REFERENCES PERIODO(idPERIODO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DETALLE_PATROCINIO (
  PATROCINIO_PATROCINADOR_idPATROCINADOR INTEGER,
  PATROCINIO_CURSO_idCURSO INTEGER,
  TIPO_PATROCINIO_idTIPO_PATROCINIO VARCHAR(20),
  cantidad INTEGER,
  PRIMARY KEY(PATROCINIO_PATROCINADOR_idPATROCINADOR, PATROCINIO_CURSO_idCURSO),
  FOREIGN KEY(PATROCINIO_CURSO_idCURSO, PATROCINIO_PATROCINADOR_idPATROCINADOR)
    REFERENCES PATROCINIO(CURSO_idCURSO, PATROCINADOR_idPATROCINADOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TIPO_PATROCINIO_idTIPO_PATROCINIO)
    REFERENCES TIPO_PATROCINIO(idTIPO_PATROCINIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION

);