CREATE TABLE USUARIO (
  login VARCHAR(20),
  password VARCHAR(20),
  PRIMARY KEY(login)
);

CREATE TABLE SESION (
  idSESION SERIAL,
  USUARIO_login VARCHAR(20),
  pid INTEGER,
  activo BOOL,
  PRIMARY KEY(idSESION, USUARIO_login),
  FOREIGN KEY(USUARIO_login)
    REFERENCES USUARIO(login)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ROL (
  idROL INTEGER,
  nombreRol VARCHAR(20),
  PRIMARY KEY(idROL)
);

CREATE TABLE TIPOIU (
  idTIPOIU INTEGER,
  nombreIU
  PRIMARY KEY(idTIPOIU)
);

CREATE TABLE FUNCION (
  idFUNCION VARCHAR(20),
  TIPOIU_idTIPOIU INTEGER,
  descripcionFuncion VARCHAR(20),
  PRIMARY KEY(idFUNCION),
  FOREIGN KEY(TIPOIU_idTIPOIU)
    REFERENCES TIPOIU(idTIPOIU)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE USUARIO_ROL (
  USUARIO_login VARCHAR(20),
  ROL_idROL INTEGER,
  PRIMARY KEY(USUARIO_login, ROL_idROL),
  FOREIGN KEY(USUARIO_login)
    REFERENCES USUARIO(login)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ROL_idROL)
    REFERENCES ROL(idROL)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ROL_FUNCION (
  ROL_idROL INTEGER,
  FUNCION_idFUNCION VARCHAR(20),
  PRIMARY KEY(ROL_idROL, FUNCION_idFUNCION),
  FOREIGN KEY(ROL_idROL)
    REFERENCES ROL(idROL)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(FUNCION_idFUNCION)
    REFERENCES FUNCION(idFUNCION)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);